spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Mkiwanz/git-config-repo
          default-label: main
          skip-ssl-validation: true
          search-paths: configs



server:
  port: 8888
